In [3]:
## Pytorch fundamentals
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.5.1


In [ ]:
##Different tensors
scalar = torch.tensor(7)
#Scalar.ndim gets the dimensions of the tensor
scalar.ndim

0

In [12]:
#scalar.item gets item as python int
scalar.item()
#vector!
vector = torch.tensor([7,7])
vector.shape

torch.Size([2])

In [20]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX[1][1]

tensor(10)

In [33]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]], [[9,8,7],
                                   [6,5,4],
                                   [3,2,1]
                                    ]])
TENSOR.shape

torch.Size([2, 3, 3])

In [42]:
#Random tensors
#Random tensors are important because they way many neural networks
#earn is they start with tensors full of random numbers and then adjust those
#random numbers
random = torch.rand(1)
random


tensor([0.6939])

In [ ]:
#reandom tensor with simialr shape to an image tensor
random_image = torch.rand(size = (224,224,3))#Height,width, color channels (R,G,B)
random_image.shape,random_image.ndim,

(torch.Size([224, 224, 3]), 3)

In [46]:
## Zeros and ones 
zeros = torch.zeros(3,4)
random = zeros * random
random

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#tensors of ones
ones = torch.ones(3,4)
ones.dtype

torch.float32

In [63]:
#creating a range of tensors and tensors-like
counting = torch.arange(start = 1,end=11,step = 1)
counting

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
ten_zeros = torch.zeros_like(counting)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#tensor datatypes
t16 = torch.tensor([3.0,6.0,9.0],dtype = torch.float16)#ensor datatype
t32 = torch.tensor([3.0,6.0,9.0],dtype = torch.float32)
tensortTest = t16 * t32
tensortTest.dtype

torch.float32

In [80]:
some_tensor = torch.rand(3,4)
print(some_tensor)
print(f"Datatype of tensor:  {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"device tensor is on: {some_tensor.device}")


tensor([[0.2224, 0.3673, 0.0011, 0.6383],
        [0.7456, 0.8219, 0.3501, 0.0138],
        [0.8877, 0.2217, 0.1142, 0.9206]])
Datatype of tensor:  torch.float32
Shape of tensor: torch.Size([3, 4])
device tensor is on: cpu


In [87]:
#tensor operations, include addition, subtraction,multiplication, division, matrix multiplication
tensor1 = torch.tensor([1,2,3])
torch.mul(tensor1,100)

tensor([100, 200, 300])

In [89]:
##Matrix multiplication, 
tensor2 = torch.tensor([3,2,1])
print(f"{tensor1 * tensor2}")
print(f"{torch.matmul(tensor1,tensor2)}")

tensor([3, 4, 3])
10


In [12]:
tensorA = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensorB = torch.tensor([[7,8],
                        [9,10],
                        [11,12]])
torch.mm(tensorA,tensorB.T)
print(f"Tensosr A og: \n{tensorA}")
print(f"TenosrA transposed: \n{tensorA.T}")

Tensosr A og: 
tensor([[1, 2],
        [3, 4],
        [5, 6]])
TenosrA transposed: 
tensor([[1, 3, 5],
        [2, 4, 6]])


In [42]:
#tensor aggregation is getting a min, max, mean, sum, etc. Remeber means need float dtype
x = torch.arange(0, 100, 11)
torch.mean(x.type(torch.float16))
x

tensor([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [75]:
#Reshaping, stacking, squeezing, and unsqueezing tensors
#reshaping: reshapes n input tensor to a certain shape
#View: returns a view of an input tensor of certian shape but keeps the same memeory as og tensor
#Stacking-combine multiple tensors on top of each other(vstack) or side by side(hsack)
#Squeeze - removes all `1` dimensions from a tensor
#unsqueeze - adds a `1` dimensions to a target tensors
#permute - return a view of the input with dimensiosns permutated in a certain way
x = torch.arange(0,11)
x.shape


torch.Size([11])

In [ ]:
x_reshape = x.view(3,2,3,2)
x_reshape.shape

torch.Size([3, 2, 3, 2])

In [88]:
xStack = torch.vstack([x,x,x,x,x,x])
xStack,xStack.ndim

(tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 2)

In [115]:
z = torch.ones(1,2,2,1,1,1)
print(f"{z}")
y = torch.squeeze(z, dim = 2)
print(f"{y}")
p = torch.unsqueeze(y, dim=6)
p

tensor([[[[[[1.]]],


          [[[1.]]]],



         [[[[1.]]],


          [[[1.]]]]]])
tensor([[[[[[1.]]],


          [[[1.]]]],



         [[[[1.]]],


          [[[1.]]]]]])


tensor([[[[[[[1.]]]],



          [[[[1.]]]]],




         [[[[[1.]]]],



          [[[[1.]]]]]]])

In [124]:
#torch.permute-rearranges the dimensions of a target
x = torch.rand(2,3,5)
print(f"{x.size()}")
y = torch.permute(x, (2, 0, 1))
x[0,0,0] = 1
x,y

torch.Size([2, 3, 5])


(tensor([[[1.0000, 0.5728, 0.2241, 0.9462, 0.0350],
          [0.9019, 0.4261, 0.2405, 0.7081, 0.2085],
          [0.1029, 0.8002, 0.3989, 0.0893, 0.7252]],
 
         [[0.9624, 0.8425, 0.7842, 0.8905, 0.2819],
          [0.1297, 0.0549, 0.2192, 0.4225, 0.8954],
          [0.8130, 0.5221, 0.2056, 0.2108, 0.0437]]]),
 tensor([[[1.0000, 0.9019, 0.1029],
          [0.9624, 0.1297, 0.8130]],
 
         [[0.5728, 0.4261, 0.8002],
          [0.8425, 0.0549, 0.5221]],
 
         [[0.2241, 0.2405, 0.3989],
          [0.7842, 0.2192, 0.2056]],
 
         [[0.9462, 0.7081, 0.0893],
          [0.8905, 0.4225, 0.2108]],
 
         [[0.0350, 0.2085, 0.7252],
          [0.2819, 0.8954, 0.0437]]]))

In [137]:
x = torch.arange(1,10).reshape(1,3,3)
x[0,0,2]

tensor(3)

In [153]:
x[:,:,2]

tensor([[3, 6, 9]])

In [175]:
#PyTorch tensors and Numpy
#often to have data in Numpy and want/need it in Pytorch tensor
#you can do `torch.from_numpy(ndarray)`
#pytorch to numpy you can do torch.tensor.numpy
import numpy as pd
array =np.arange(0.0,11.0)
tensor = torch.from_numpy(array).type(torch.float32)
print(f"{array}")
print(f"{tensor}")
#When going from nump to pytoch, pytorch reflects numpys default datatype of float64 unless specified
array = array + 1
print(f"{array}\n{tensor}")
#going to tensor back to numpy
tensor = torch.ones(5).type(torch.int32)
array = tensor.numpy()
tensor = tensor + 1
tensor,array


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


(tensor([2, 2, 2, 2, 2], dtype=torch.int32),
 array([1, 1, 1, 1, 1], dtype=int32))

In [177]:
#Reproducability: trying to take the random out of random
#To reduce randomness in neural networks and pytorch comes the comcept of random seed
#random seed  "flavors" The randomness.
rand1 = torch.rand(3,4)
rand2 = torch.rand(3,4)
print(rand1 == rand2)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [179]:
#sets random seed 
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
rand3 = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
rand4 = torch.rand(3,4)
print(rand3 == rand4)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
